"""Initial migration

Revision ID: 28461a4310f5
Revises: 
Create Date: 2026-03-23 21:46:56.283859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28461a4310f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('value_bets', sa.Column('is_stale', sa.Boolean(), nullable=False))
    op.add_column('value_bets', sa.Column('intelligence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('value_bets', 'intelligence_score')
    op.drop_column('value_bets', 'is_stale')
    # ### end Alembic commands ###
